### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by simongui** [yarpc/yab#119]
I'm getting the following after running this.

```
go get -u -f github.com/yarpc/yab

package github.com/yarpc/yab
	imports github.com/yarpc/yab/encoding
	imports github.com/yarpc/yab/thrift
	imports github.com/thriftrw/thriftrw-go/envelope
	imports go.uber.org/thriftrw/internal/envelope/exception: use of internal package not allowed
```

**Comment by breerly** [comment]
Looks like we are pinning to thriftrw-go master, our fault!

We'll pin to the last known working version from here :)

**Comment by prashantv** [comment]
@simongui The `glide.lock` pins to specific versions that `yab` will build against, we haven't updated dependencies (that's planned soon, will be done in #114). It is expected that `go get` may fail, and there's no way to guarantee it won't due to `go get` only relying on master of every repository.

You can use the prebuild binaries in [Releases](https://github.com/yarpc/yab/releases), or if you'd like to build your own binary, you'll need to have [glide installed](https://github.com/Masterminds/glide), then do:
```
$ go get -d github.com/yarpc/yab
$ cd $GOPATH/src/github.com/yarpc/yab
$ glide install
$ go install .
```

@breerly `go get` does not look at `glide.yaml` or `glide.lock`, Glide doesn't really have a solution for executables that people `go get`. There's no `glide get` to get a repository, and use the pins to install it.

Since `yab` is not a library, I actually would prefer `glide.yaml` to have `master`, since we should be updating to `master` on every `glide up` so that it's more likely for `go get` to work.

**Comment by simongui** [comment]
I'm not sure I agree here. Glide supports vendoring and the purpose of vendoring is to check in the vendoring directory so that `go get` works. Isn't that supposed to be how it works? Having a go repository not support `go get` is kind of difficult to use, isn't it?

**Comment by prashantv** [comment]
Glide supports vendoring, and while checking in vendor is one approach, there are some issues with that approach. Checking in the vendor directory actually breaks things if part of the repository can be used as a subpackage and a dependency's types are exported (see point 14 [here](https://peter.bourgon.org/go-best-practices-2016/)).

There are also possible licensing issues with checking in the vendor directory ([discussed briefly here](http://engineeredweb.com/blog/2016/go-why-not-strip-unused-pkgs/)).

And in terms of usability, vendoring makes code reviews more difficult, and ends up bloating the repository.

It's impossible to support `go get` 100% of the time because it's not possible to make an atomic breaking API change across repos. We should try to keep `master` working against the latest `master` of all dependencies to make it easier to `go get`, and that work is already being tracked in the issue I mentioned earlier, #114.

Until `go get` supports real package management, I don't think we'll have a real solution to these problems.
