### ISSUE TITLE
request deadline is initialized too early

### ISSUE THREAD

**Issue by eklitzke** [yarpc/yab#143]
I noticed that when I specify a timeout of 2s, the actual header that is sent by Yab is `Context-Ttl-Ms: 1999`. This is because the code sets a "deadline" on the context object, and then uses that deadline for each request. Therefore any time that elapses between when the deadline is calculated and when Yab actually schedules the first request will be subtracted from the request time.

I think this is counter-intuitive. The deadline should be computed at the same time the first request is made, not before.

**Comment by prashantv** [comment]
When you specify a timeout of 2s, the timeout applies to the whole request -- which includes other creating a TCP connection to the remote side. In tcurl, we had separate TCP connection timeouts vs the request timeout send to the the remote side (see https://github.com/uber/tcurl/issues/131), which only caused confusion for users.

From a user's perspective, if they say "make a request with a 1s timeout", it's strange for it to take 1.5 seconds because 0.5 seconds were spent in the TCP connection phase.

The Go ecosystem uses `net/context` to propagate timeout values across call boundaries, and these are based on a similar assumption - the caller is basically specifying a deadline for everything, rather than a specific header value.

From a user's perspective, when they're debugging it may look a little strange to see `1999` instead of `2000` for a 2s timeout, but the overall end user experience is more intuitive when the timeout includes everything.

**Comment by eklitzke** [comment]
I'll defer to you if you think this is invalid, but my objection isn't to including TCP setup costs or other network transport times. My objection is that the deadline is set when the context object is created, rather than right before the first network call. There's other stuff that happens in between when the context object is created (e.g. initializing tracer spans) and when the first request with the context actually happens.

**Comment by prashantv** [comment]
Yep, we do some extra work, which is only setting up the tracing spans,
```go
	ctx, cancel := tchannel.NewContext(request.Timeout)
	defer cancel()

	if tracer := t.Tracer(); tracer != nil {
		span := tracer.StartSpan(request.Method)
		opentracing_ext.SamplingPriority.Set(span, trace)
		for k, v := range request.Baggage {
			span = span.SetBaggageItem(k, v)
		}
		ctx = opentracing.ContextWithSpan(ctx, span)
	}

	return t.Call(ctx, request)

```

We could change it to instead create a sub-context with the span, and then create a sub-context off that for the call. However it'll make the code a little more verbose, and will probably only save a few microseconds.

The reason you saw `Context-Ttl-Ms: 1999` (from the original issue description) is most likely because of the connection time, I'm not sure making the code more verbose will really help here.
