### ISSUE TITLE
add "sk" tchannel header support

### ISSUE THREAD

**Issue by blampe** [yarpc/yab#98]
This could be a hidden option. Sorry if we already support this -- it looks like it might fit into `--topt` but I didn't dig in.

**Comment by prashantv** [comment]
Yep it's a hidden option under `--topt` right now, you can specify either the shard key or the routing delegate by adding:
```
--topt sk:1234567 --topt rd:crossdc-router
```

I didn't want to expose a `--sk` or `--rd` flag since it's TChannel specific. It's a little obscure to use the `topt` option, but we can add some documentation for it instead.

**Comment by blampe** [comment]
Ah great makes sense, thanks! Docs aren't too urgent so I'll close this out for now.
